application: pyexp5448
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
    -   name: django
        version: "1.3"

env_variables:
    DJANGO_SETTINGS_MODULE: '5448.settings'

handlers:
    -   url: /.*
        script: 5448.wsgi.application

builtins:
    -   django_wsgi: on
