# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2 
  database: first_project_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  host: localhost
  password: 
  reconnect: false

test:
  adapter: mysql2 
  database: first_project_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  host: localhost
  password: 
  reconnect: false

production:
  adapter: mysql2 
  database: first_project_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  host: localhost
  password: 
  reconnect: false

